from flowchart_builder import generate_drawio_xml

nodes = [
    {"id": "n1", "label": "Start", "shape": "start_end"},
    {"id": "n2", "label": "Parent/Child chunks saved & approved in PostgreSQL\n\nInitial State:\nocr_status = done\nreview_status = approved\nrag_status = not_indexed or failed\ningestion_job.current_step = chunks_approved", "shape": "env"},
    {"id": "n3", "label": "Admin opens Index & publish page", "shape": "process"},
    {"id": "n4", "label": "System checks:\n- OCR completed\n- Canonical Markdown approved\n- Chunks approved\n- Document version not indexed", "shape": "process"},
    {"id": "n5", "label": "Eligible for Indexing?", "shape": "decision"},
    {"id": "n6", "label": "Disable “Start Indexing” button", "shape": "process"},
    {"id": "n7", "label": "Require returning to incomplete step", "shape": "process"},
    
    {"id": "n8", "label": "Admin clicks “Start Indexing”", "shape": "process"},
    {"id": "n9", "label": "POST /document-versions/{id}/index", "shape": "io"},
    {"id": "n10", "label": "Backend locks document version", "shape": "process"},
    {"id": "n11", "label": "Check status:\n- ocr_status = done\n- review_status = approved\n- rag_status = not_indexed or failed\n- current_step = chunks_approved", "shape": "process"},
    {"id": "n12", "label": "Read approved Parent/Child chunks from PostgreSQL", "shape": "process"},
    {"id": "n13", "label": "Chunks exist & quantity sufficient?", "shape": "decision"},
    
    {"id": "n14", "label": "Block Indexing", "shape": "process"},
    {"id": "n15", "label": "Require previewing & approving chunks again", "shape": "process"},
    
    {"id": "n16", "label": "Read canonical Markdown from R2", "shape": "process"},
    {"id": "n17", "label": "Reconstruct chunk structure for verification", "shape": "process"},
    {"id": "n18", "label": "Compare with approved chunks:\n- Chunk key\n- Parent relation\n- Chunk index\n- Content\n- Heading path\n- Page range\n- Token count", "shape": "process"},
    {"id": "n19", "label": "Matches approved chunk set?", "shape": "decision"},
    
    {"id": "n20", "label": "Block Indexing", "shape": "process"},
    {"id": "n21", "label": "Require previewing & approving chunks again", "shape": "process"},
    
    {"id": "n22", "label": "Create indexing job:\n- job_type = indexing\n- status = processing\n- current_step = embedding\n- total_chunks = Child chunk count\n- processed_chunks = 0\n- started_at = current timestamp", "shape": "process"},
    {"id": "n23", "label": "Update rag_status = chunked", "shape": "process"},
    {"id": "n24", "label": "Return HTTP 202 to frontend", "shape": "io"},
    {"id": "n25", "label": "Run indexing in background", "shape": "process"},
    {"id": "n26", "label": "Frontend polls job status every second", "shape": "process"},
    {"id": "n27", "label": "Generate embeddings for Child chunks", "shape": "process"},
    {"id": "n28", "label": "Update processed_chunks by batch", "shape": "process"},
    {"id": "n29", "label": "Embedding successful?", "shape": "decision"},
    
    {"id": "n30", "label": "job.status = failed\njob.current_step = failed\nrag_status = failed\nSave error_message", "shape": "process"},
    {"id": "n31", "label": "Admin can Retry Indexing", "shape": "process"},
    
    {"id": "n32", "label": "job.current_step = qdrant_upsert", "shape": "process"},
    {"id": "n33", "label": "Retrieve PostgreSQL chunk IDs:\n- postgres_chunk_id\n- postgres_parent_chunk_id", "shape": "process"},
    {"id": "n34", "label": "Upsert Child vectors into Qdrant:\n- Vector embedding\n- Structural payload\n- review_status = approved\n- rag_status = indexed\n- Do not store content in Qdrant", "shape": "process"},
    {"id": "n35", "label": "Qdrant upsert successful?", "shape": "decision"},
    
    {"id": "n36", "label": "job.status = failed\njob.current_step = failed\nrag_status = failed\nSave error_message", "shape": "process"},
    {"id": "n37", "label": "Admin can Retry Indexing", "shape": "process"},
    
    {"id": "n38", "label": "PostgreSQL Transaction:\n- document_chunks.index_status = indexed\n- Save qdrant_point_id\n- document_version.rag_status = indexed\n- job.status = completed\n- job.current_step = completed\n- processed_chunks = total_chunks\n- finished_at = current timestamp", "shape": "env"},
    {"id": "n39", "label": "Frontend displays Indexing completed", "shape": "process"},
    {"id": "n40", "label": "Admin inspects indexing result", "shape": "process"},
    {"id": "n41", "label": "Admin clicks “Publish document”", "shape": "process"},
    {"id": "n42", "label": "POST /versions/{id}/publish", "shape": "io"},
    {"id": "n43", "label": "rag_status = indexed?", "shape": "decision"},
    
    {"id": "n44", "label": "Block Publish\nDisplay status error", "shape": "process"},
    
    {"id": "n45", "label": "Update PostgreSQL:\n- rag_status = published\n- published_at = current timestamp", "shape": "process"},
    {"id": "n46", "label": "Update Qdrant payload:\n- rag_status = published", "shape": "process"},
    {"id": "n47", "label": "Qdrant update successful?", "shape": "decision"},
    
    {"id": "n48", "label": "Rollback PostgreSQL:\n- rag_status = indexed\n- Remove published_at", "shape": "process"},
    {"id": "n49", "label": "Display error\nAdmin can Retry Publish", "shape": "process"},
    
    {"id": "n50", "label": "Document Published", "shape": "process"},
    {"id": "n51", "label": "Document eligible for Retrieval:\n- review_status = approved\n- rag_status = published\n- Matching Audience", "shape": "env"},
    {"id": "n52", "label": "Chatbot can utilize document", "shape": "process"},
    {"id": "n53", "label": "Completed", "shape": "start_end"},
]

edges = [
    {"source": "n1", "target": "n2"},
    {"source": "n2", "target": "n3"},
    {"source": "n3", "target": "n4"},
    {"source": "n4", "target": "n5"},
    {"source": "n5", "target": "n6", "label": "No"},
    {"source": "n6", "target": "n7"},
    {"source": "n5", "target": "n8", "label": "Yes"},
    {"source": "n8", "target": "n9"},
    {"source": "n9", "target": "n10"},
    {"source": "n10", "target": "n11"},
    {"source": "n11", "target": "n12"},
    {"source": "n12", "target": "n13"},
    {"source": "n13", "target": "n14", "label": "No"},
    {"source": "n14", "target": "n15"},
    {"source": "n13", "target": "n16", "label": "Yes"},
    {"source": "n16", "target": "n17"},
    {"source": "n17", "target": "n18"},
    {"source": "n18", "target": "n19"},
    {"source": "n19", "target": "n20", "label": "No"},
    {"source": "n20", "target": "n21"},
    {"source": "n19", "target": "n22", "label": "Yes"},
    {"source": "n22", "target": "n23"},
    {"source": "n23", "target": "n24"},
    {"source": "n24", "target": "n25"},
    {"source": "n25", "target": "n26"},
    {"source": "n26", "target": "n27"},
    {"source": "n27", "target": "n28"},
    {"source": "n28", "target": "n29"},
    {"source": "n29", "target": "n30", "label": "No"},
    {"source": "n30", "target": "n31"},
    {"source": "n29", "target": "n32", "label": "Yes"},
    {"source": "n32", "target": "n33"},
    {"source": "n33", "target": "n34"},
    {"source": "n34", "target": "n35"},
    {"source": "n35", "target": "n36", "label": "No"},
    {"source": "n36", "target": "n37"},
    {"source": "n35", "target": "n38", "label": "Yes"},
    {"source": "n38", "target": "n39"},
    {"source": "n39", "target": "n40"},
    {"source": "n40", "target": "n41"},
    {"source": "n41", "target": "n42"},
    {"source": "n42", "target": "n43"},
    {"source": "n43", "target": "n44", "label": "No"},
    {"source": "n43", "target": "n45", "label": "Yes"},
    {"source": "n45", "target": "n46"},
    {"source": "n46", "target": "n47"},
    {"source": "n47", "target": "n48", "label": "No"},
    {"source": "n48", "target": "n49"},
    {"source": "n47", "target": "n50", "label": "Yes"},
    {"source": "n50", "target": "n51"},
    {"source": "n51", "target": "n52"},
    {"source": "n52", "target": "n53"},
]

generate_drawio_xml(nodes, edges, "05_Index_Publish.drawio")
print("Generated diagram 05 in English")
