from flowchart_builder import generate_drawio_xml

# 1. uc_upload_prepare_doc
nodes1 = [
    {"id": "n1", "label": "Start", "shape": "start_end"},
    {"id": "n2", "label": "Admin opens Document Processing page", "shape": "process"},
    {"id": "n3", "label": "Markdown file available?", "shape": "decision"},
    {"id": "n4", "label": "Upload Markdown", "shape": "process"},
    {"id": "n5", "label": "Upload source file if any", "shape": "process"},
    {"id": "n6", "label": "Enter metadata", "shape": "process"},
    {"id": "n7", "label": "Select OCR?", "shape": "decision"},
    {"id": "n8", "label": "Stay on upload page", "shape": "process"},
    {"id": "n9", "label": "Open separate OCR page\nDo not carry file from upload page", "shape": "process"},
    {"id": "n10", "label": "Upload new PDF/DOC/DOCX/PPT/PPTX/Image", "shape": "process"},
    {"id": "n11", "label": "Start OCR", "shape": "process"},
    {"id": "n12", "label": "OCR successful?", "shape": "decision"},
    {"id": "n13", "label": "Display error", "shape": "process"},
    {"id": "n14", "label": "Retry or select another file", "shape": "process"},
    {"id": "n15", "label": "Display metadata form\nDisplay Markdown result", "shape": "process"},
    {"id": "n16", "label": "Admin enters metadata", "shape": "process"},
    {"id": "n17", "label": "Admin reviews/edits Markdown", "shape": "process"},
    {"id": "n18", "label": "Admin clicks “Save and continue”", "shape": "process"},
    {"id": "n19", "label": "Validate Markdown and metadata", "shape": "process"},
    {"id": "n20", "label": "Data valid?", "shape": "decision"},
    {"id": "n21", "label": "Display error", "shape": "process"},
    {"id": "n22", "label": "Admin edits data", "shape": "process"},
    {"id": "n23", "label": "Save source file (if any) to R2\nSave canonical Markdown to R2\nCreate document/version/job in PostgreSQL", "shape": "env"},
    {"id": "n24", "label": "Proceed to Review & approve", "shape": "process"},
    {"id": "n25", "label": "End UC Upload", "shape": "start_end"}
]
edges1 = [
    {"source": "n1", "target": "n2"},
    {"source": "n2", "target": "n3"},
    {"source": "n3", "target": "n4", "label": "Yes"},
    {"source": "n4", "target": "n5"},
    {"source": "n5", "target": "n6"},
    {"source": "n6", "target": "n18"},
    {"source": "n3", "target": "n7", "label": "No"},
    {"source": "n7", "target": "n8", "label": "No"},
    {"source": "n8", "target": "n18"},
    {"source": "n7", "target": "n9", "label": "Yes"},
    {"source": "n9", "target": "n10"},
    {"source": "n10", "target": "n11"},
    {"source": "n11", "target": "n12"},
    {"source": "n12", "target": "n13", "label": "No"},
    {"source": "n13", "target": "n14"},
    {"source": "n14", "target": "n10"},
    {"source": "n12", "target": "n15", "label": "Yes"},
    {"source": "n15", "target": "n16"},
    {"source": "n16", "target": "n17"},
    {"source": "n17", "target": "n18"},
    {"source": "n18", "target": "n19"},
    {"source": "n19", "target": "n20"},
    {"source": "n20", "target": "n21", "label": "No"},
    {"source": "n21", "target": "n22"},
    {"source": "n22", "target": "n18"},
    {"source": "n20", "target": "n23", "label": "Yes"},
    {"source": "n23", "target": "n24"},
    {"source": "n24", "target": "n25"}
]
generate_drawio_xml(nodes1, edges1, "01_uc_upload_prepare_doc.drawio")

# 2. uc_review_approve_file
nodes2 = [
    {"id": "n1", "label": "Start", "shape": "start_end"},
    {"id": "n2", "label": "Admin opens Review & approve page", "shape": "process"},
    {"id": "n3", "label": "System displays:\n- Status\n- Metadata\n- Files/Markdown", "shape": "process"},
    {"id": "n4", "label": "Admin reviews document\nand edits (if needed)", "shape": "process"},
    {"id": "n5", "label": "Admin clicks “Save & approve to Review chunks”", "shape": "process"},
    {"id": "n6", "label": "Frontend validates data", "shape": "process"},
    {"id": "n7", "label": "Frontend data valid?", "shape": "decision"},
    {"id": "n8", "label": "Display error\nAdmin continues editing", "shape": "process"},
    {"id": "n9", "label": "Send review API request", "shape": "process"},
    {"id": "n10", "label": "Backend finds document version", "shape": "process"},
    {"id": "n11", "label": "Document version exists?", "shape": "decision"},
    {"id": "n12", "label": "Return not found error", "shape": "process"},
    {"id": "n13", "label": "rag_status = not_indexed?", "shape": "decision"},
    {"id": "n14", "label": "Block Review/Approve\nRequire Deindex first", "shape": "process"},
    {"id": "n15", "label": "Backend validation", "shape": "process"},
    {"id": "n16", "label": "Backend data valid?", "shape": "decision"},
    {"id": "n17", "label": "Return validation/conflict error", "shape": "process"},
    {"id": "n18", "label": "Create & save new revision to R2", "shape": "process"},
    {"id": "n19", "label": "R2 save successful?", "shape": "decision"},
    {"id": "n20", "label": "Retain old data\nDisplay error", "shape": "process"},
    {"id": "n21", "label": "PostgreSQL Transaction\nUpdate data & status", "shape": "env"},
    {"id": "n22", "label": "Transaction successful?", "shape": "decision"},
    {"id": "n23", "label": "Delete newly created R2 revision\nDisplay error", "shape": "process"},
    {"id": "n24", "label": "Delete old canonical revision (R2)\nFrontend updates status", "shape": "process"},
    {"id": "n25", "label": "Proceed to Review chunks", "shape": "process"},
    {"id": "n26", "label": "End", "shape": "start_end"}
]
edges2 = [
    {"source": "n1", "target": "n2"},
    {"source": "n2", "target": "n3"},
    {"source": "n3", "target": "n4"},
    {"source": "n4", "target": "n5"},
    {"source": "n5", "target": "n6"},
    {"source": "n6", "target": "n7"},
    {"source": "n7", "target": "n8", "label": "No"},
    {"source": "n8", "target": "n4"},
    {"source": "n7", "target": "n9", "label": "Yes"},
    {"source": "n9", "target": "n10"},
    {"source": "n10", "target": "n11"},
    {"source": "n11", "target": "n12", "label": "No"},
    {"source": "n11", "target": "n13", "label": "Yes"},
    {"source": "n13", "target": "n14", "label": "No"},
    {"source": "n13", "target": "n15", "label": "Yes"},
    {"source": "n15", "target": "n16"},
    {"source": "n16", "target": "n17", "label": "No"},
    {"source": "n17", "target": "n4"},
    {"source": "n16", "target": "n18", "label": "Yes"},
    {"source": "n18", "target": "n19"},
    {"source": "n19", "target": "n20", "label": "No"},
    {"source": "n20", "target": "n4"},
    {"source": "n19", "target": "n21", "label": "Yes"},
    {"source": "n21", "target": "n22"},
    {"source": "n22", "target": "n23", "label": "No"},
    {"source": "n23", "target": "n4"},
    {"source": "n22", "target": "n24", "label": "Yes"},
    {"source": "n24", "target": "n25"},
    {"source": "n25", "target": "n26"}
]
generate_drawio_xml(nodes2, edges2, "03_uc_review_approve_file.drawio")

# 3. uc_chunk_approve
nodes3 = [
    {"id": "n1", "label": "Start", "shape": "start_end"},
    {"id": "n2", "label": "Admin opens Review chunks page", "shape": "process"},
    {"id": "n3", "label": "Canonical Markdown approved?", "shape": "decision"},
    {"id": "n4", "label": "Block Review chunks\nRequire returning to previous step", "shape": "process"},
    {"id": "n5", "label": "Admin clicks “Generate chunk preview”", "shape": "process"},
    {"id": "n6", "label": "Backend generates chunk preview\n(Parse Markdown, create temporary chunks)", "shape": "process"},
    {"id": "n7", "label": "Frontend displays:\nChunk list, warnings, errors", "shape": "process"},
    {"id": "n8", "label": "Has errors?", "shape": "decision"},
    {"id": "n9", "label": "Disable “Save & approve” button\nAdmin returns to edit Markdown", "shape": "process"},
    {"id": "n10", "label": "Has warnings?", "shape": "decision"},
    {"id": "n11", "label": "Admin reviews warnings\nand decides to proceed", "shape": "process"},
    {"id": "n12", "label": "Admin clicks “Save and approve chunks”", "shape": "process"},
    {"id": "n13", "label": "Backend re-validates", "shape": "process"},
    {"id": "n14", "label": "New chunking errors?", "shape": "decision"},
    {"id": "n15", "label": "Reject approval\nReturn error", "shape": "process"},
    {"id": "n16", "label": "Document modified since preview?", "shape": "decision"},
    {"id": "n17", "label": "Reject approval\nRequire generating preview again", "shape": "process"},
    {"id": "n18", "label": "PostgreSQL Transaction\n- Delete old chunks\n- Save Parent & Child chunks\n- Update ingestion job", "shape": "env"},
    {"id": "n19", "label": "Frontend saves state", "shape": "process"},
    {"id": "n20", "label": "Proceed to Index & publish", "shape": "process"},
    {"id": "n21", "label": "End", "shape": "start_end"}
]
edges3 = [
    {"source": "n1", "target": "n2"},
    {"source": "n2", "target": "n3"},
    {"source": "n3", "target": "n4", "label": "No"},
    {"source": "n3", "target": "n5", "label": "Yes"},
    {"source": "n5", "target": "n6"},
    {"source": "n6", "target": "n7"},
    {"source": "n7", "target": "n8"},
    {"source": "n8", "target": "n9", "label": "Yes"},
    {"source": "n8", "target": "n10", "label": "No"},
    {"source": "n10", "target": "n11", "label": "Yes"},
    {"source": "n11", "target": "n12"},
    {"source": "n10", "target": "n12", "label": "No"},
    {"source": "n12", "target": "n13"},
    {"source": "n13", "target": "n14"},
    {"source": "n14", "target": "n15", "label": "Yes"},
    {"source": "n14", "target": "n16", "label": "No"},
    {"source": "n16", "target": "n17", "label": "Yes"},
    {"source": "n16", "target": "n18", "label": "No"},
    {"source": "n18", "target": "n19"},
    {"source": "n19", "target": "n20"},
    {"source": "n20", "target": "n21"}
]
generate_drawio_xml(nodes3, edges3, "04_uc_chunk_approve.drawio")

# 4. unpublish_version
nodes4 = [
    {"id": "n1", "label": "Start", "shape": "start_end"},
    {"id": "n2", "label": "Admin selects document version", "shape": "process"},
    {"id": "n3", "label": "Admin selects Deindex / Unpublish", "shape": "process"},
    {"id": "n4", "label": "Display confirmation notice", "shape": "process"},
    {"id": "n5", "label": "Admin confirms?", "shape": "decision"},
    {"id": "n6", "label": "Cancel operation", "shape": "process"},
    {"id": "n7", "label": "Is indexing job running?", "shape": "decision"},
    {"id": "n8", "label": "Block operation", "shape": "process"},
    {"id": "n9", "label": "rag_status is\nchunked/embedded/indexed/published?", "shape": "decision"},
    {"id": "n10", "label": "Notify document is not indexed", "shape": "process"},
    {"id": "n11", "label": "Create deindex job", "shape": "env"},
    {"id": "n12", "label": "Delete vectors from Qdrant", "shape": "process"},
    {"id": "n13", "label": "Deletion successful?", "shape": "decision"},
    {"id": "n14", "label": "job_status = failed\nAllow retry", "shape": "process"},
    {"id": "n15", "label": "Delete chunks from PostgreSQL", "shape": "process"},
    {"id": "n16", "label": "Update status\nrag_status = not_indexed", "shape": "env"},
    {"id": "n17", "label": "Deindex Completed", "shape": "start_end"}
]
edges4 = [
    {"source": "n1", "target": "n2"},
    {"source": "n2", "target": "n3"},
    {"source": "n3", "target": "n4"},
    {"source": "n4", "target": "n5"},
    {"source": "n5", "target": "n6", "label": "No"},
    {"source": "n5", "target": "n7", "label": "Yes"},
    {"source": "n7", "target": "n8", "label": "Yes"},
    {"source": "n7", "target": "n9", "label": "No"},
    {"source": "n9", "target": "n10", "label": "No"},
    {"source": "n9", "target": "n11", "label": "Yes"},
    {"source": "n11", "target": "n12"},
    {"source": "n12", "target": "n13"},
    {"source": "n13", "target": "n14", "label": "No"},
    {"source": "n13", "target": "n15", "label": "Yes"},
    {"source": "n15", "target": "n16"},
    {"source": "n16", "target": "n17"}
]
generate_drawio_xml(nodes4, edges4, "02_unpublish_version.drawio")

print("Generated diagrams 01, 02, 03, 04 in English")
